### PR TITLE
Style downloader settings

### PR DESCRIPTION
**Pull request by Araxeus**

### CODE REVIEW

**Comment by Inrixia** [comment]
Can you provide a screenshot of what this changes please.

**Comment by Araxeus** [comment]
## before

image

image

## after (but before spacing commit)

image

image

## Final result (after spacing commit)

image

image

**Comment by Inrixia** [comment]
Spacing is fine. But the background is hard to make out. Ideally it would be a much lighter grey. Adding a style override would fix this, or just remove the styling for the background specifically

**Comment by Araxeus** [comment]
You're right, but the question now would be what shade to use exactly, I pushed a new version that looks ok to me, let me know what you think:

image

image

**Comment by Inrixia** [comment]
Looks good.

Though ideally fix the white line at the end of the text input.

Other than that I could nit about other things but it's outside the scope of this pr.

**Comment by Araxeus** [comment]
fixed (and removed a useless style)

image

**Comment by Inrixia** [comment]
Awesome thx

**Pull request merged**
